version: '3.8'

services:
  app:
    image: would-you-rather-web-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/wouldyouratheroptions
      SPRING_DATASOURCE_USERNAME: Admin
      SPRING_DATASOURCE_PASSWORD: Knight!5179
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wouldyouratheroptions
      MYSQL_USER: Admin
      MYSQL_PASSWORD: Knight!5179
    ports:
      - "3306:3306"  # MySQL port
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
