package edu.carroll.cs389.web.controller;


import edu.carroll.cs389.jpa.model.Question;
import edu.carroll.cs389.jpa.repo.QuestionRepository;
import edu.carroll.cs389.service.QuestionService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.carroll.cs389.web.form.WouldYouRatherForm;
import jakarta.validation.Valid;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

@Controller
public class WouldYouRatherController {


    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private final QuestionService questionService = new QuestionService();

    @GetMapping("/wouldYouRatherEntry")
    public String optionsGet(Model model) {
        model.addAttribute("wouldYouRatherForm", new WouldYouRatherForm());
        return "WouldYouRatherEntry";
    }

    @PostMapping("/wouldYouRatherEntry")
//
    public String optionsPost(@RequestParam String optionA, @RequestParam String optionB, @ModelAttribute WouldYouRatherForm wouldYouRatherForm, Model model) {
        model.addAttribute("wouldYouRatherForm", wouldYouRatherForm);
        Question newEntry = new Question(optionA, optionB);
        System.out.println(optionA+"  "+optionB);
        questionService.addQuestion(newEntry);
        return "WouldYouRatherEntry";
    }

}